services:
  club:
    build: .
    restart: unless-stopped
    labels:
      - "project=club-dev"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py tailwind install &&
             python manage.py tailwind start & 
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - SECRET=your-dev-secret
      - DATABASE_URL=postgres://clubuser:clubpass@db:5432/clubdb

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_DB=clubdb
      - POSTGRES_USER=clubuser
      - POSTGRES_PASSWORD=clubpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clubuser -d clubdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./form_submissions:/import:ro # added in this line to mount form submissions directory
    # Optional: expose for local tools like psql/GUI
    ports:
      - "5432:5432"

volumes:
 pgdata: