# docker-compose.dev.yml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

    env_file:
      - .env

    container_name: club_web_dev

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    environment:
      - DEBUG=1

    command: >
      sh -c "
        # Run tailwind install (idempotent, ensures node_modules)
        python manage.py tailwind install &&
        # Start the tailwind watcher in the background
        python manage.py tailwind dev
      "

    tty: true
    stdin_open: true
