# Generated by Django 4.2.23 on 2025-09-02 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRosterRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('completion_time', models.DateTimeField()),
                ('school_email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Returning', 'Returning')], max_length=10)),
                ('club_join_date', models.DateField()),
                ('major', models.TextField()),
                ('exp_grad_date', models.IntegerField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('added_to_comm_channels', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberZipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10)),
                ('member_count', models.IntegerField(default=0)),
            ],
        ),
    ]
