# Generated by Django 4.2.23 on 2025-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boardmemberdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmemberdata',
            name='board_position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
